HoiskolensChemikerforening/hc-backend

- chemie/committees/templates/committees/view_committee.html
- chemie/committees/views.py
- chemie/customprofile/views.py
- chemie/events/views.py
- chemie/lockers/admin.py
- chemie/lockers/models.py
- chemie/lockers/templates/lockers/list.html
- chemie/lockers/tests.py
- chemie/lockers/views.py
- chemie/news/templates/news/list.html
- chemie/news/views.py
- chemie/picturecarousel/views.py
- chemie/shitbox/templates/shitbox/post_form.html
- chemie/shitbox/views.py
Adds consistency for permissions and should make locker management easier.
> Carl fixes

- chemie/committees/admin.py
- chemie/committees/factories.py
- chemie/committees/forms.py
- chemie/committees/models.py
- chemie/committees/templates/committees/edit_committee_members.html
- chemie/committees/templates/committees/edit_description.html
- chemie/committees/templates/committees/view_committee.html
- chemie/committees/tests.py
- chemie/committees/urls.py
- chemie/committees/views.py
- chemie/customprofile/factories.py
- chemie/requirements.txt
Many improvements for the committee app. 
- Allows many users per position 
- Can set a max-user on group
- Better permission handling
- Unit tests
> Committee update

- chemie/customprofile/templates/customprofile/editprofile.html
- chemie/events/templates/events/admin_list.html
- chemie/events/views.py
Waiting list was added for the table sorter at the administration panel for events. Only those who can administer registrations have permission to view the waiting list.
> <-- Waiting List -->

- chemie/home/models.py
Some bank account id's start with 0. int(bank_account_id) removes this leading zero, so that the length of the id is effectively 10. Added functionality for starting the id with 0.
> Fundsapplication

- chemie/chemie/templates/chemie/base.html
> Add link to logo text :)

- Dockerfile
- chemie/chemie/settings/local.py
- chemie/committees/templates/committees/edit_committee_members.html
- requirements/base.in
- requirements/development.txt
Burde være fiksa nå. Var bare å fjerne en god del av eksisterende snusk samt følge standard oppsett av pluginen på nytt.
> Fix edit members in committees app

- chemie/chemie/settings/__init__.py
- requirements/base.in
- requirements/development.in
Removed Carl's cute brainfart and moved factoryboy to development requirements only.
> Minor change to requirements and init settings

- chemie/chemie/urls.py
- chemie/customprofile/forms.py
- chemie/customprofile/models.py
- chemie/customprofile/templates/customprofile/register.html
- chemie/customprofile/templates/registration/login.html
- chemie/customprofile/templates/registration/terms_and_conditions.html
- chemie/customprofile/views.py
> [WIP] Require consent upon login

- chemie/chemie/templates/chemie/index.html
- chemie/events/templates/events/frontpage_events.html
- chemie/events/templates/events/frontpage_list_events.html
- chemie/home/templates/home/post_funds_form.html
- chemie/news/templates/news/detail.html
- chemie/news/templates/news/frontpage_news.html
Brought frontpage-improvements up to date combined with some minor quickfixes.
> Frontpage-improvements and quickfixes

- chemie/news/templates/news/detail.html
Added author and date created below article content, as well as a breadcrumb trail on the news_detail page
> Added news breadcrumb, author and date created

- chemie/events/forms.py
- chemie/events/models.py
- chemie/events/templates/events/bedpres/detail.html
- chemie/events/templates/events/list_events.html
- chemie/events/templates/events/social/detail.html
New branch identical to first one to skip merge conflict
> Events without registration v2

- chemie/elections/templates/elections/admin/admin_candidates.html
- chemie/elections/templates/elections/admin/admin_positions.html
- chemie/elections/templates/elections/admin/admin_results.html
- chemie/elections/templates/elections/election/resultater.html
- chemie/elections/templates/elections/election/vote.html
- chemie/elections/tests/test_views.py
- chemie/elections/views.py
implementation of feedback from beta-testing
> [WIP] Elections ui iteration

- chemie/customprofile/views.py
> Important import for ProfileManager to fix bug

- chemie/chemie/templates/chemie/contact.html
Updated the text on the contact page, making it clear that it can be used to report inappropriate behavior anonymically etc.
> Update text on contact page

- chemie/customprofile/views.py
- chemie/elections/views.py
- chemie/events/views.py
When Student card nr is not registered, the student card is sent to the add_rfid view.
> Reduce scanning

- chemie/quiz/templates/quiz/create_score.html
Minor fix, improves user experience.
> Hotfix for checkbox on edit quiz-page

- chemie/chemie/urls.py
- chemie/shop/templates/shop/add_category.html
- chemie/shop/templates/shop/add_item.html
- chemie/shop/templates/shop/admin.html
- chemie/shop/templates/shop/all_receipts.html
- chemie/shop/templates/shop/all_refills.html
- chemie/shop/templates/shop/base_shop.html
- chemie/shop/templates/shop/edit_item.html
- chemie/shop/templates/shop/happy-hour.html
- chemie/shop/templates/shop/refill-balance.html
- chemie/shop/templates/shop/shop.html
- chemie/shop/templates/shop/user_receipts.html
- chemie/shop/templates/shop/user_refills.html
- chemie/shop/templates/shop/user_statistics.html
- chemie/shop/views.py
Minor improvements to the shop. Add default view for admin to see all receipts and refill when not selected any users. Add nav bar title, minor typos fix.
> Shop features improvements

- chemie/chemie/templates/chemie/base.html
Quick hotfix, should be able to merge quickly :D
> Fixed problem with footer stemming form earlier merge

- chemie/web_push/models.py
> Update timer to 15 min for CoffeSubmission model

- chemie/committees/templates/committees/edit_committee_members.html
Collapsable sidenav now functioning as intended on https://hc.ntnu.no/verv/_navn-på-verv_/edit-members/
> Remove unnecessary JS file so that navbar JS works as intended

- chemie/home/templates/home/post_funds_form.html
Can somebody plese review my pull request and accept it? I would really appreciate it.
> Changed text in application for funding

- chemie/events/templates/events/register_user.html
Linkene til samtykkeerklæringen og Indkoms prikkesystem var defekte etter at det ble rydda opp i wikien. Nå skal de vise til rett plass.
> Update event links

- chemie/chemie/settings/local.py
Makes database connection possible on Linux.
> Add localhost to local settings

- chemie/lockers/templates/lockers/list.html
- chemie/lockers/urls.py
- chemie/lockers/views.py
- chemie/picturecarousel/templates/picturecarousel/approve.html
- chemie/picturecarousel/templates/picturecarousel/view_active.html
- chemie/picturecarousel/urls.py
- chemie/picturecarousel/views.py
- chemie/shitbox/templates/shitbox/list_submissions.html
- chemie/shitbox/urls.py
- chemie/shitbox/views.py
The pagination broke when the URLs were changed from url() to path(). It seems like (in the Django documentation) that the proper way to do this is to use GET parameters.
> Fix broken pagination

- chemie/lockers/forms.py
- chemie/sugepodden/models.py
- chemie/sugepodden/urls.py
- chemie/sugepodden/views.py
> [WIP] Fix linting on all files

- chemie/corporate/templates/corporate/base.html
- chemie/corporate/templates/corporate/job_advertisement.html
- chemie/corporate/views.py
Fixed a typo in the permission check, so that indkom members may add and delete job advertisments. Also added a link to the home page from corporate pages.
> Fix corporate permissions

- chemie/chemie/settings/base.py
Does the settings file need more changes?
> Fixed a change in the settings/base

- chemie/events/templates/events/attendees.html
- chemie/events/templates/events/social/deregister_or_edit.html
- chemie/events/templates/events/social/detail.html
- chemie/events/views.py
In the future, a Registration object should be created for each user added to a group. I will list this as a further improvement in issue #332.
> Display users registered to event as a group in "Påmeldte" list.

- chemie/corporate/forms.py
- chemie/corporate/templates/corporate/interview_detail.html
- chemie/corporate/templates/corporate/interview_edit.html
- chemie/corporate/urls.py
- chemie/corporate/views.py
Finished edit interview functionality for indkom interviews.
> Edit corporate interview

- chemie/chemie/templates/404.html
> Remove image text.

- chemie/customprofile/templates/customprofile/memberships.html
- chemie/customprofile/urls.py
- chemie/customprofile/views.py
I've used alot of the same code as the catalog app, so there is alot of improvements to be made. Nice if someone could look for possiblities to shorten the code somewhere. Further the plan is to give options to give out either 1, 2, 3, 4, 5 or "lifetime" memberships to users. Maybe it's cleanest to have a dropdown on the red button to give out the different varities of membership. Any feedback would be appreciated!
> [WIP] Add functionality to sort users by grade

- chemie/events/migrations/0010_auto_20211009_1823.py
- chemie/rentalservice/migrations/0001_initial.py
This is to fix inconsistencies between the server and the GitHub repo
> Fix inconsistencies with migrations

- chemie/corporate/views.py
Fixed typo in permission check. Changed from ':' to '.'
> Fix permissions issue on corporate page

- chemie/corporate/templates/corporate/job_detail.html
`perms.corporate.edit_job` was not the correct permission name. Should be `change_job` instead.
> Fix edit job permission

- chemie/news/models.py
Defined max length in slug for news url
> Fix slug variable in news model

- chemie/customprofile/templates/customprofile/register.html
Added a javascript function block at the end of the html file.
> Fix pop up bug for terms and conditions on registration

- chemie/committees/views.py
It is now possible to search for both first name and last name in the search bar.
> Fix search bar query

- chemie/elections/templates/elections/admin/admin_positions.html
- chemie/elections/urls.py
- chemie/elections/views_admin.py
Need this feature for CGP so that we don't have to scan all the student cards
> Add button to make all users eligible for voting

- chemie/shop/views.py
Reverts HoiskolensChemikerforening/hc-backend#420
> Revert "Make all shop items available for all users"

- chemie/chemie/urls.py
- chemie/committees/templates/committees/list_committees.html
Change names of page and url to keep website more consistent
> Change name from Komiteer to Undergrupper

- chemie/merch/templates/merch/detail.html
- chemie/merch/templates/merch/list_all_categories.html
- chemie/merch/views.py
Fixed a little whoopsie
Piping hot PR for the lucky one!!
> Fix permission bug for merch and category

- chemie/customprofile/templates/customprofile/yearbook.html
Added specialisations to person detail in yearbook so it shows that person specialization, only if the person has one
> Add specialization on yearbook profile card detail

- chemie/events/models.py
Changed models file in event so the function "get_allowed_grades_display(self)" displays "all" instead of "first, second, thid, fourth, fifth" when all classes are allowed to join a bedpress.
> Change detalview events

- chemie/events/templates/events/bedpres/deregister_or_edit.html
- chemie/events/templates/events/register_user.html
- chemie/events/templates/events/social/deregister_or_edit.html
I have added the link to the terms for events to more than just the registration form. Now you can view them even when the registration isn't open and when you are deregestering yourself.
> Rettningslinjer

- chemie/shop/templates/shop/add_item.html
- chemie/shop/views.py
Added filter button to shop admin items
> Shop changes

- chemie/customprofile/templates/customprofile/yearbook.html
changed button layout for year done
> change format of buttons for year done

- chemie/chemie/templates/chemie/base.html
- chemie/chemie/templates/chemie/index.html
- chemie/events/templates/events/bedpres/bedpres_base.html
- chemie/events/templates/events/bedpres/create.html
- chemie/events/templates/events/bedpres/delete.html
- chemie/events/templates/events/bedpres/deregister_or_edit.html
- chemie/events/templates/events/bedpres/detail.html
- chemie/events/templates/events/bedpres/list.html
- chemie/events/templates/events/bedpres/permissions.html
- chemie/events/templates/events/frontpage_list_events.html
- chemie/events/views.py
Changed the use of "bedpres" to "karriere" or  "arrangement"
> Change bedpress word

- chemie/events/templates/events/social/deregister_or_edit.html
added flex wrap to allow overflow to next row
> Fix Event deregister button for small screens

- chemie/events/templates/events/bedpres/create.html
- chemie/events/templates/events/register_user.html
> fix breacrumbs bug that links to wrong event type

- chemie/chemie/static/css/electofood.css
- chemie/electofood/templates/electofeed.html
- chemie/electofood/views.py
> Fix valgomat

- chemie/events/views.py
Redirect from registration page to detail page to avoid confusion. Hard to test if it works because of missing email template locally
> change register url

- chemie/chemie/static/css/style.css
- chemie/chemie/templates/chemie/index.html
Fix mobile view for  countdown
> mobile fix

- chemie/customprofile/models.py
- chemie/customprofile/templates/customprofile/yearbook.html
Added a new relationship status "HC incest".
> Added a color for HC incest relationship status

- chemie/rentalservice/templates/rentalservice/contact_page.html
- chemie/rentalservice/urls.py
> change spelling

- chemie/refund/templates/annual_report.html
- chemie/refund/views.py
Automaticly populate the account number field with the account number used in the last refund request created by the currently logged in user.
> Refund account number

- chemie/events/views.py
change order of my earlier events list
> change past event order

- chemie/customprofile/templates/customprofile/yearbook.html
Add so you can view details of a person that does not have a picture
> Yearbook popup

- chemie/chemie/templates/chemie/index.html
commented out the countdown to remove from website. but can be used later if necessary
> coment out countdown

- chemie/committees/templates/committees/email_download.html
- chemie/committees/templates/committees/view_committee.html
- chemie/committees/urls.py
- chemie/committees/views.py
Download every committee member email as a csv file. May need to look into permissions
> Emaildownload

- chemie/customprofile/models.py
Changed HC incest to HC forhold
> remove incest from HC

- chemie/chemie/static/css/style.css
- chemie/chemie/static/js/makeItRain.js
- chemie/chemie/templates/chemie/base.html
> Make it rain
